### ISSUE TITLE
Homebrew gflags has no `libgflags.pc`

### ISSUE THREAD

**Issue by msbit** [google/guetzli#61] opened 2017-03-18 01:42 UTC
Building from master (`c78689c5e020c0cd3580783213798b6323eaa454`) on macOS gives me the following error:

```
==== Building guetzli (release) ====
Creating obj/Release
butteraugli_comparator.cc
Package libgflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgflags' found

...snip...

butteraugli.cc
Package libgflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgflags' found
Linking guetzli
Package libgflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgflags' found
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)", referenced from:
      __GLOBAL__sub_I_guetzli.cc in guetzli.o
  "google::FlagRegisterer::FlagRegisterer<double>(char const*, char const*, char const*, double*, double*)", referenced from:
      __GLOBAL__sub_I_guetzli.cc in guetzli.o
  "google::SetUsageMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in guetzli.o
  "google::ShowUsageWithFlags(char const*)", referenced from:
      _main in guetzli.o
  "google::ParseCommandLineFlags(int*, char***, bool)", referenced from:
      _main in guetzli.o
  "_png_create_info_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_create_read_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_destroy_read_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_channels", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_image_height", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_image_width", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_rows", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_init_io", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_read_png", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_set_longjmp_fn", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/Release/guetzli] Error 1
make: *** [guetzli] Error 2
```

As part of the Homebrew gflags package, the pkg-config file is `gflags.pc`, not `libgflags.pc` so the build process can't set up the build flags properly.

**Comment by pornel** [comment] 2017-03-18 01:44
Known problem - #55

**Comment by robryk** [comment] 2017-03-18 02:15
Fixed by #62. Sorry for the trouble I've caused by introducing this.

**Closed by robryk** 2017-03-18 02:15 UTC

**Comment by msbit** [comment] 2017-03-18 02:18
@robryk 👌 
No stress, thanks for the quick merge.

**Comment by donat-b** [comment] 2017-03-20 06:26
Similar problem on Gentoo with dev-cpp/gflags-2.1.1-r1
How to tell what name needs pkg-config?

```==== Building guetzli (release) ====
Linking guetzli
Package gflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `gflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gflags' found```

**Comment by msbit** [comment] 2017-03-20 12:16
@donat-b you could do something like:

```
$ sudo updatedb
$ locate gflags.pc
```

If that doesn't return a file (for me it returns `/usr/lib/arm-linux-gnueabihf/pkgconfig/libgflags.pc` which indicates `libgflags` instead of `gflags`), then that basically means that your package doesn't include a pkg-config definition. This is the case with `gflags` < 2.2 if installed vanilla, which I imagine Gentoo does.

In that case, you'll have to follow something like the MacPorts instructions in the README, adding `CFLAGS` and `LDFLAGS` before the `make` command, so something like:

`CFLAGS='-I${prefix}/include' LDFLAGS='-L${prefix}/lib' make`

where `prefix` is the base for where the package is installed, commonly `/usr`, `/usr/local` or `/opt`.

Good luck!

**Comment by donat-b** [comment] 2017-03-20 19:48
@msbit 
I've looked at the list of files and it actually doesn't include the .pc file. Well, turns out they have removed the gflags dependency after all these reports. Your help is much appreciated nonetheless. :)

**Comment by msbit** [comment] 2017-03-20 20:59
@donat-b Oh, that's one way to fix the problem!
