### ISSUE TITLE
improve the speed 

### ISSUE THREAD

**Issue by WangWenchao** [google/guetzli#73] opened 2017-03-18 11:41 UTC
I use it optmize file about 200k used almost 80s 

<img width="969" alt="screen shot 2017-03-18 at 7 34 18 pm" src="https://cloud.githubusercontent.com/assets/576604/24071664/ae2caa6e-0c12-11e7-903c-9dc7115f37a9.png">

**Comment by Smilebags** [comment] 2017-03-18 11:50
It isn't a simple problem. Yes, having it faster would be good but there is lots to consider when 'improving the speed'. It currently only runs on one core and as far as I know, doesn't use the GPU. Have a read through the older issues regarding speed to get to know the issue more.

**Comment by JackRo** [comment] 2017-03-18 12:12
only jpg to jpg is not fast, but the png to jpg and the png to png is so fast, png to png is right by the guetzli?

**Comment by pornel** [comment] 2017-03-18 12:55
Dupe of #50

**Closed** 2017-03-18 13:23 UTC
