### ISSUE TITLE
The encode time is too long for guetzli method

### ISSUE THREAD

**Issue by dongjinguang-china** [google/guetzli#115] opened 2017-03-22 07:17 UTC
Hi friends,

    Now I have build a guetzli tool on Ubuntu 14.04 env. when I compress a JPEG to new JPEG , the compress size is very significant. But the consume time is too long, about 20mins.  Could tell me why we need to do so many Iter ,which form 1 to 37 .

     Now we want to port this method to android platform, whether is it  have optimization method to improve time consume?

**Comment by dongjinguang-china** [comment] 2017-03-22 07:18
Please ref to attachment log ,
[run-log.txt](https://github.com/google/guetzli/files/860590/run-log.txt)

**Comment by bdkjones** [comment] 2017-03-22 08:57
Duplicate of #24.

**Closed** 2017-03-22 15:08 UTC
Labels: duplicate

**Comment by robryk** [comment] 2017-03-22 15:10
You can see reported sizes and Butteraugli distances in each line of debug output:


>Iter 10: f111111(7) up Coeffs[24885/45016] Blocks[1287/1797/1848] ValThres[0.7288] Out[  **46401**] EstErr[0.10%] BA[100.00%] D[**1.0452**] Score[1820309.3844]


We just need that many iterations to arrive at a small enough JPEG at the requested quality.
